apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: social-health-check
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 80
